site_name: Savant Lighting and Shades
site_url: https://example.com


theme:
    name: material
    logo: img/logo.png
    favicon: assets/logo.png

    palette:
     #   scheme: savants
    - primary: light blue

    
    features:
    - navigation.sections
   # - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    
markdown_extensions:
  - attr_list
  
plugins:
    - search
    - mkdocs-pdf
    - open-in-new-tab
   
  
extra:
  generator: false

    
nav:
    - 'Home': 'index.md'
    
    - 'Design': 
      - '': product/index.md
      - Network: product/network.md
      - Ligthing: product/lighting.md
      - Shades: product/shading.md
      - Tools: product/tools.md

    - 'Installation':
      - Wireless Lighting:
        - 'ignored': builder/index.md
        - 'Wiring': builder/wiring.md
        - 'Quick Start Guide': builder/quickstartguide.md
        - 'Deployment Guides': builder/deployment.md

      - Shades:
        - 'ignored': builder/index.md
        - 'Wiring': builder/wiring.md
        - 'Quick Start Guide': builder/quickstartguide.md
        - 'Deployment Guides': builder/deployment.md

      - Wired Lighting:
        - 'ignored': builder/index.md
        - 'Wiring': builder/wiring.md
        - 'Quick Start Guide': builder/quickstartguide.md
        - 'Deployment Guides': builder/deployment.md

    - 'Programming':
        - Setup:
            - '': programming/index.md #this is normal yaml
            - 'SAM': programming/sam.md
            - 'Blueprint': programming/blueprint.md

        - Blueprint:
            - '': programming/index.md #this is normal yaml
            - 'Quickstart': programming/quickstart.md
            - 'Zones': programming/zones.md
            - 'Keypad Discovery': programming/discovery.md
            - 'Deploy': programming/deploy.md
            - 'Help Sections': programming/help.md

    - 'Resources':
          - 'ignored': rresources/index.md
          - 'Videos': rresources/index.md
          - 'FAQs': rresources/faqs.md
          - 'Glossary': builder/glossary.md
     
extra_css:
    - style.css
    
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
    #extra_css:
     #   - stylesheets/extra.css
