site_name: Savant Lighting and Shades
site_url: https://example.com


theme:
    name: material
    logo: img/logo.png
    favicon: assets/logo.png

    palette:
     #   scheme: savants
    - primary: light blue

    
    features:
    - navigation.sections
   # - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    
markdown_extensions:
  - attr_list
  
plugins:
    - search
    - mkdocs-pdf
    - open-in-new-tab
   
  
extra:
  generator: false

    
nav:
    - 'Home': 'index.md'
    - 'Product':
        - '': product/index.md

    - 'Programming':
        - Blueprint:
            - '': programming/index.md #this is normal yaml
            - 'Help Sections': programming/help.md
   
   
    - 'Electrician & Builder':
        - Installation:
            - '': builder/index.md
            - 'Wiring': builder/wiring.md
            - 'Quick Start Guide': builder/quickstartguide.md
            - 'Deployment Guides': builder/deployment.md
            - 'Glossary': builder/glossary.md


    - 'Training':
        - '':
            - '': builder/training.md

     
extra_css:
    - style.css
    
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
    #extra_css:
     #   - stylesheets/extra.css
