site_name: Savant Lighting and Shades
site_url: https://example.com


theme:
    name: material
    logo: img/logo.png
    favicon: assets/logo.png

    palette:
     #   scheme: savants
    - primary: light blue

    
    features:
    - navigation.sections
   # - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    
markdown_extensions:
    - attr_list
    - toc:
        permalink:
  
plugins:
    - search
    - mkdocs-pdf
    - open-in-new-tab
    - mkdocs-video
  
extra:
  generator: false

    
nav:
    - 'Home': 'index.md'
    
    - 'Design': 
      - '': product/index.md
      - Network: product/network.md
      - Ligthing: product/lighting.md
      - Shades: product/shading.md
      - Tools: product/tools.md

    - 'Installation':
      - '': installation/index.md
      - Network: installation/network.md
      - Lighting: installation/lighting.md
      - Shades: installation/shading.md
      - Archived pages:
        - 'Wiring': installation/wiring.md
        - 'Quick Start Guide': installation/quickstartguide.md
        - 'Deployment Guides': installation/deployment.md

    - 'Programming':
        - '': programming/index.md #this is normal yaml
        - Computer Setup: programming/sam.md
        - Network: programming/network.md
        - Pre-Program Lighting: programming/lighting.md
        - Pre-Program Shades: programming/shading.md
        - Configuration Software: programming/blueprint.md
        - Configuring a Home: programming/zones.md
        - End User App: programming/proapp.md
        - Achived pages:
            - 'Keypad Discovery': programming/discovery.md
            - 'Deploy': programming/deploy.md
            - 'Help Sections': programming/help.md

    - 'Resources':
          - '': rresources/index.md
          - 'Videos': rresources/index.md
          - 'FAQs': rresources/faqs.md
          - 'Glossary': installation/glossary.md
          - Blueprint Contextual Help:
              - 'Help Index': help/helpindex.md 
              - 'BACNet': help/bacnet.md 
              - 'Component': help/component.md 
              - 'ComponentPallette': help/componentpallette.md 
              - 'DataTable': help/datatable.md 
              - 'Document': help/document.md 
              - 'Energy': help/energy.md 
              - 'Find': help/find.md 
              - 'General': help/general.md 
              - 'HVAC': help/hvac.md 
              - 'Inspector': help/inspector.md 
              - 'Logs': help/logs.md
              - 'Lighting': help/lighting.md
              - 'Preferences': help/preferences.md 
              - 'Profiles': help/profiles.md
              - 'Reports': help/reports.md 
              - 'Security': help/security.md 
              - 'Services': help/services.md 
              - 'Settings': help/settings.md 
              - 'States': help/states.md 
              - 'Workflows': help/workflows.md 
              - 'Zones': help/zones.md 

     
extra_css:
    - style.css
    
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
    #extra_css:
     #   - stylesheets/extra.css
