site_name: Savant Lighting and Shades
site_url: https://example.com


theme:
    name: material
    logo: img/logo.png
    favicon: assets/logo.png

    palette:
     #   scheme: savants
    - primary: light blue

    
    features:
    - navigation.sections
   # - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    
markdown_extensions:
    - attr_list
  
plugins:
    - search
    - mkdocs-pdf
    - open-in-new-tab
    - mkdocs-video
  
extra:
  generator: false

    
nav:
    - 'Home': 'index.md'
    
    - 'Design': 
      - '': design/index.md
#      - Network: design/network.md
      - Ligthing: design/lighting.md
#      - Shades: design/shading.md
      - Tools: design/tools.md

    - 'Installation':
      - '': installation/index.md
#      - Network: installation/network.md
      - Lighting: installation/lighting.md
#      - Shades: installation/shading.md
#      - Archived pages:
#        - 'Wiring': installation/wiring.md
#        - 'Quick Start Guide': installation/quickstartguide.md
#        - 'Deployment Guides': installation/deployment.md

    - 'Programming':
        - '': programming/index.md #this is normal yaml
        - Computer Setup: programming/sam.md
#        - Network: programming/network.md
        - Pre-Program Lighting: programming/lighting.md
#        - Pre-Program Shades: programming/shading.md
        - Configuration Software: programming/blueprint.md
        - Configuring a Home: programming/zones.md
        - End User App: programming/proapp.md
#        - Achived pages:
#            - 'Keypad Discovery': programming/discovery.md
#            - 'Deploy': programming/deploy.md
#            - 'Help Sections': programming/help.md

#    - 'Resources':
#          - '': rresources/index.md
#          - 'Videos': rresources/index.md
#          - 'FAQs': rresources/faqs.md
#          - 'Glossary': installation/glossary.md
     
extra_css:
    - style.css
    
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  
    #extra_css:
     #   - stylesheets/extra.css
